package com.mintech.parkwiseapp.ui.screens

import android.content.Context
import android.util.Log
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.CircularProgressIndicator
import androidx.compose.material.Icon
import androidx.compose.material.Text
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Security
import androidx.compose.material.icons.filled.Shield
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.blur
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.messaging.FirebaseMessaging
import com.mintech.parkwiseapp.R
import com.mintech.parkwiseapp.services.ApiService
import com.mintech.parkwiseapp.services.GoogleLoginRequest
import com.mintech.parkwiseapp.ui.theme.*
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await

@Composable
fun LoginScreen(onLoginSuccess: () -> Unit) {
    var isLoading by remember { mutableStateOf(false) }
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()

    // 1. Configure Google Sign-In Options
    // 'default_web_client_id' is automatically generated by your google-services.json!
    val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
        .requestIdToken(context.getString(R.string.default_web_client_id))
        .requestEmail()
        .requestProfile()
        .build()

    val googleSignInClient = remember { GoogleSignIn.getClient(context, gso) }

    // 2. Handle the Result from the Google Popup
    val launcher = rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
        val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
        try {
            val account = task.getResult(ApiException::class.java)

            // We successfully got the Google Account, now send it to Node.js
            coroutineScope.launch {
                try {
                    // Fetch the FCM token for VoIP pushes
                    val fcmToken = FirebaseMessaging.getInstance().token.await()

                    val payload = GoogleLoginRequest(
                        email = account.email ?: "",
                        name = account.displayName ?: "Parkwise User",
                        googleId = account.id ?: "",
                        fcmToken = fcmToken,
                        voipToken = "", // Android doesn't use VoIP tokens, FCM does both!
                        photoUrl = account.photoUrl?.toString() ?: ""
                    )

                    // Send to backend
                    val response = ApiService.api.loginWithGoogle(payload)

                    // Save session exactly like the Swift app
                    val prefs = context.getSharedPreferences("AppPrefs", Context.MODE_PRIVATE)
                    prefs.edit()
                        .putString("jwt_token", response.token)
                        .putString("user_id", response.user._id)
                        .putString("user_email", response.user.email)
                        .apply()

                    isLoading = false
                    onLoginSuccess() // Navigate to Dashboard!

                } catch (e: Exception) {
                    Log.e("AuthError", "Failed to login with backend", e)
                    isLoading = false
                }
            }
        } catch (e: ApiException) {
            Log.e("AuthError", "Google Sign-In failed", e)
            isLoading = false
        }
    }

    // --- UI STARTS HERE ---
    Box(modifier = Modifier.fillMaxSize().background(Background)) {
        Box(
            modifier = Modifier
                .size(400.dp)
                .offset(x = 200.dp, y = (-100).dp)
                .background(Color(0xFF234720).copy(alpha = 0.5f), CircleShape)
                .blur(80.dp)
        )

        Column(modifier = Modifier.fillMaxSize(), horizontalAlignment = Alignment.Start) {
            Text("Parkwise", color = PrimaryApp, fontSize = 24.sp, fontWeight = FontWeight.ExtraBold, modifier = Modifier.padding(top = 48.dp, start = 24.dp))
            Spacer(modifier = Modifier.weight(1f))

            Column(modifier = Modifier.padding(horizontal = 24.dp).padding(bottom = 48.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {

                Row(modifier = Modifier.background(SurfaceHigh, RoundedCornerShape(20.dp)).border(1.dp, OnSurfaceVariant.copy(alpha = 0.3f), RoundedCornerShape(20.dp)).padding(horizontal = 12.dp, vertical = 8.dp), verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Filled.Security, contentDescription = null, tint = PrimaryApp, modifier = Modifier.size(14.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("SECURE ACCESS", color = OnSurfaceVariant, fontSize = 10.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.5.sp)
                }

                Text("Hassle Free\nCommunication", color = Color.White, fontSize = 44.sp, fontWeight = FontWeight.ExtraBold, lineHeight = 48.sp)
                Text("Sign in to manage your vehicle emergency contacts and secure your roadside response.", color = OnSurfaceVariant, fontSize = 16.sp)
                Spacer(modifier = Modifier.height(32.dp))

                Column(modifier = Modifier.background(SurfaceLowest, RoundedCornerShape(28.dp)).padding(32.dp), verticalArrangement = Arrangement.spacedBy(24.dp)) {

                    // 3. The Clickable Login Button
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .border(1.dp, OnSurfaceVariant.copy(alpha = 0.5f), RoundedCornerShape(12.dp))
                            .clickable(enabled = !isLoading) {
                                isLoading = true
                                // FIRE THE GOOGLE INTENT!
                                launcher.launch(googleSignInClient.signInIntent)
                            }
                            .padding(vertical = 16.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        if (isLoading) {
                            CircularProgressIndicator(color = Color.White, modifier = Modifier.size(24.dp), strokeWidth = 2.dp)
                        } else {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                // Fallback generic user icon if Google logo isn't in your drawables
                                Text("G", color = Color.Red, fontSize = 24.sp, fontWeight = FontWeight.Bold)
                                Spacer(modifier = Modifier.width(12.dp))
                                Text("Sign in with Google", color = Color.White, fontSize = 16.sp, fontWeight = FontWeight.Bold)
                            }
                        }
                    }

                    Row(modifier = Modifier.fillMaxWidth().background(SurfaceLow, RoundedCornerShape(12.dp)).border(1.dp, OnSurfaceVariant.copy(alpha = 0.2f), RoundedCornerShape(12.dp)).padding(16.dp)) {
                        Icon(Icons.Filled.Shield, contentDescription = null, tint = Color(0xFF8B9BA5), modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(12.dp))
                        Column {
                            Text("Data Privacy", color = Color.White, fontSize = 14.sp, fontWeight = FontWeight.Bold)
                            Text("Your vehicle data and contact list are encrypted.", color = OnSurfaceVariant, fontSize = 12.sp)
                        }
                    }
                }
            }
        }
    }
}